services:
  database:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db_test
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_mysql_test # データベース名
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin # ユーザー名（任意）
      MYSQL_PASSWORD: password # ユーザーのパスワード（任意）
    volumes:
      - ./volumes/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./volumes/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"

  php-apache:
    platform: linux/x86_64
    container_name: php_apache_test
    build:
      context: ./php
    ports:
      - "8000:80" # localhost:8000でアクセスできる
    volumes:
      - ./src:/var/www/test
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database # databaseに後に実行する
